[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[env]
RUST_LIB_BACKTRACE = "1"
RUST_BACKTRACE = "1"

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=getrandom_backend=\"wasm_js\"", "--cfg=web_sys_unstable_apis"]

# macOS / Linux 交叉编译 Windows 平台需要指定Linker和AR
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"
